name: Lint Rust Code with Cargo and Prek

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  prek-lint:
    uses: George-Ogden/actions/.github/workflows/lint.yaml@v4.6.1

  cargo-lint:
    uses: George-Ogden/actions/.github/workflows/rust-lint.yaml@v4.6.1
    with:
      rust-version: stable
